# Generated by Django 5.2.7 on 2026-05-22 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_order_ref', models.CharField(max_length=100)),
                ('operative_name', models.CharField(max_length=100)),
                ('arrived_time', models.TimeField()),
                ('departed_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(choices=[('cherry_picker_full', 'Cherry picker (full day)'), ('cherry_picker_half', 'Cherry picker (half day)'), ('cable_drum', 'Cable drum'), ('road_saw', 'Road saw'), ('compactor', 'Compactor plate'), ('generator', 'Generator (day rate)'), ('traffic_mgmt', 'Traffic management kit'), ('sds_drill', 'SDS drill set'), ('pipe_freeze', 'Pipe freezing kit'), ('laser_level', 'Laser level kit')], max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('transit_van', 'Transit van'), ('tipper_35t', '3.5t tipper'), ('lorry_75t', '7.5t lorry'), ('cherry_truck', 'Cherry picker truck'), ('car_suv', 'Car / SUV')], max_length=50)),
                ('registration', models.CharField(max_length=20)),
                ('arrived_time', models.TimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
